guest_que = []
print(guest_que)
print("adding 2 guests")
guest_que.append("**001")
guest_que.append("**002")
print(guest_que)
print("inserting high priority guest")
guest_que.insert(0, "**003")
print(guest_que)
print("adding 3 more guests")
guest_que.append("**004")
guest_que.append("**005")
guest_que.append("**006")
print(guest_que)
done = guest_que.pop(0)
print(f"{done} is served.")
print(guest_que)
canceled = guest_que.pop()
print(f"{canceled} has canceled.")
print(guest_que)
